---
abstract: 'Provides PERL_MAGIC_ext manipulators for XS modules'
author:
  - 'Goro Fuji (gfx) <gfuji(at)cpan.org>.'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::CBuilder: 0
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.2
  Test::More: 0.88
  XSLoader: 0.08
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: XS::MagicExt
name: XS-MagicExt
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/Perl-XS-MagicExt.git
version: 0.02
